### ISSUE TITLE
how i run it

### ISSUE THREAD

**Issue by evanraft** [apmoore1/semeval#2]
hello ! can you tell my how i can run the code ? when i run the run.py it displays this:
Traceback (most recent call last):
  File "semeval/examples/run.py", line 6, in <module>
    from semeval.lstms.EarlyStoppingLSTM import EarlyStoppingLSTM
ImportError: No module named 'semeval'

**Comment by apmoore1** [comment]
Hi,

You need to run it from the top level of the git repository directory like so:
``` bash
python ./examples/run.py
```

Also if you then get the following error:
``` bash
ValueError: numpy.ufunc has the wrong size, try recompiling.
```
I have updated the [requirements](https://github.com/apmoore1/semeval/blob/master/requirements.txt) file with a fixed version of numpy which should resolve this problem, so just re-install the pips like so:
``` bash
pip install -r requirements.txt
```

Hope that helps :slightly_smiling_face:
